version: 2.1

orbs:
  go: circleci/go@1.7.0

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - go/load-cache:
          key: go-mod-v4-{{ checksum "go.sum" }}  
      - run:
          name: Install Dependencies
          command: go mod download
      - go/save-cache:
          key: go-mod-v4-{{ checksum "go.sum" }} 
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports

workflows:
  sample:
    jobs:
      - build

